---
title: Gaussian Processes
author:  Matt Brigida 
date: 
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---


## Data 

We'll pull crude oil and natural gas data from the EIA's API.

```{r eval=FALSE}
library(devtools)
library(GauPro)

install_github("Matt-Brigida/EIAdata", ref = "v2_fix")

library(EIAdata)

key <- source("~/eia_key")$value

weekly_ng <- getEIA("NG.RNGC1.W", key=key)
weekly_cl <- getEIA("PET.RCLC1.W", key=key)

data <- merge.xts(weekly_ng, weekly_cl, join="inner")
data
## write to csv to also test in python-------
write.zoo(data, "./ng_cl_data.csv", sep=",")
```

We'll convert the data into logs and plot:

```{r}
data_post_2000 <- data['2000-01-01/']
ng <- as.numeric(data_post_2000$NG.RNGC1.W)
lng <- log(as.numeric(data_post_2000$NG.RNGC1.W))
cl <- as.numeric(data_post_2000$PET.RCLC1.W)
lcl <- log(as.numeric(data_post_2000$PET.RCLC1.W))

# plot(cl, ng)
plot(lcl, lng)
```

<!--- see vignettes here: https://cran.r-project.org/package=GauPro -->

<!---
## levels------

gp <- GauPro(as.numeric(data$NG.RNGC1.W), as.numeric(data$PET.RCLC1.W), parallel=FALSE)

gp$predict(5.33)
gp$predict(3.33)
gp$predict(2.33)
gp$predict(1.33)

plot(gp)

## try exponential kernel-----
kern.exp <- Exponential$new(0)
gpk.exp <- GauPro_kernel_model$new(matrix(as.numeric(data$NG.RNGC1.W), ncol=1), as.numeric(data$PET.RCLC1.W), kernel=kern.exp, parallel=FALSE)
plot(gpk.exp)

gpk.exp$predict(2.33)
-->


# Gaussian Regression

```{r}
gpl <- GauPro(lcl, lng, parallel=FALSE)
plot(gpl)
```
We can get a prediction given an input point:

```{r}
gpl$predict(2.)
```

However we also get a standard error for the prediction (`se` below).

```{r}
gpl$predict(2., se=TRUE)
```

```{r}
gpl$predict(3.)
```
```{r}
gpl$predict(4.)
```

```{r}
kern.exp <- Exponential$new(0)
gpk.exp <- GauPro_kernel_model$new(matrix(lcl, ncol=1), lng, kernel=kern.exp, parallel=FALSE)
plot(gpk.exp)



```{r}
gpk.exp$predict(2.)
```
```{r}
gpk.exp$predict(3.)
```
```{r}
gpk.exp$predict(4.)
```
